apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django.fullname" . }}-worker
  labels:
    {{- include "django.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-1"
data:
{{- range $k, $v := .Values.env.normal }}
  {{ $k }}: {{ $v | quote }}
{{- end }}